name: "Coding Standards"

on:
  pull_request:
  push:

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2, cs2pr

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

      - name: "Install locked dependencies"
        run: "composer install --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --prefer-dist"

      - name: "Coding Standard"
        run: "vendor/bin/phpcs -q --report=checkstyle | cs2pr"
