name: "Static Analysis by Psalm"

on:
  pull_request:
  push:

jobs:
  static-analysis-psalm:
    name: "Static Analysis by Psalm"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
          - "locked"
        php-version:
          - "7.4"
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --prefer-dist --prefer-lowest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --prefer-dist"

      - name: "Install locked dependencies"
        if: ${{ matrix.dependencies == 'locked' && matrix.php-version == '8.0' }}
        run: "composer install --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --prefer-dist"

      - name: "psalm"
        run: "vendor/bin/psalm --output-format=github --shepherd --stats"
